### ISSUE TITLE
readCreateProcessWithExitCode error when running

### ISSUE THREAD

**Issue by cah6** [facebookincubator/retrie#1]
Installed using `cabal install`, running in my project throws an error:
```
$ retrie --adhoc "foo = bar"
retrie: hg: readCreateProcessWithExitCode: runInteractiveProcess: exec: does not exist (No such file or directory)
```

This is on mac; installed using `cabal-install-3.0.0.0`. Installed into `~/.local/bin/retrie`. 

Possibly this is due to how I installed? My haskell projects usually use nix, so I ran `cabal install retrie` in the nix shell for my current project, which means it used the cabal, ghc, and haskell libraries in scope for that project. I did this because if I clone this library locally and run `cabal install retrie`, the output is:
```
Resolving dependencies...
Starting     profunctors-5.5.2
Starting     semigroupoids-5.3.4
Starting     haskell-src-exts-1.23.0
Building     profunctors-5.5.2
Failed to install haskell-src-exts-1.23.0
Build log ( /Users/christian.henry/.cabal/logs/ghc-8.6.5/haskell-src-exts-1.23.0-IvjfjJasXCo89gWhp1TrsK.log ):
cabal: Entering directory '/var/folders/2h/zy33qgm159g_38tk6sz3smww0000gq/T/cabal-tmp-37144/haskell-src-exts-1.23.0'
Configuring haskell-src-exts-1.23.0...
cabal: The program 'happy' version >=1.19 is required but it could not be
found.

cabal: Leaving directory '/var/folders/2h/zy33qgm159g_38tk6sz3smww0000gq/T/cabal-tmp-37144/haskell-src-exts-1.23.0'
Building     semigroupoids-5.3.4
Completed    profunctors-5.5.2
Completed    semigroupoids-5.3.4
cabal: Error: some packages failed to install:
haskell-src-exts-1.23.0-IvjfjJasXCo89gWhp1TrsK failed during the configure
step. The exception was:
ExitFailure 1
retrie-0.1.0.0-4UjPhVuPyRI377UGCyO4BA depends on retrie-0.1.0.0 which failed
to install.
```

**Comment by xich** [comment]
Well, the first error:

```
retrie: hg: readCreateProcessWithExitCode: runInteractiveProcess: exec: does not exist (No such file or directory)
```

is telling you that you don't have `hg` installed. We really only need one or the other (hg or git), so I can fix the error handling there.

The second error looks like you need to `cabal install happy` first. It looks like it is required for `haskell-src-exts`, but cabal can't figure out to install it for you.

**Comment by cah6** [comment]
Ah I see, didn't realize that's what the `hg` was. Installed it and it worked, thanks! Closing.
