### ISSUE TITLE
Support command-line rewrite equations for types

### ISSUE THREAD

**Issue by maurges** [facebookincubator/retrie#13]
I can currently get by with a hack: add `type Have x y = Want Something y x` in some module, then use `retrie --type-forward Some.Module.Have`.
It would be nice if I could do this without modifying my files.

**Comment by xich** [comment]
@d86leader Just landed a commit which adds an `--adhoc-type` flag to do this. I usually make monthly releases to hackage, but you can build from github in the meantime. Thanks for the suggestion!
