### ISSUE TITLE
Parse error on type application on constructors

### ISSUE THREAD

**Issue by anka-213** [facebookincubator/retrie#16]
Here is an example:

`Issue16.hs`
```haskell
module Issue16 (example) where

import Data.Proxy

example :: Proxy Int
example = Proxy @Int
```

```bash
$ retrie -u Issue16.example --target-file Issue16.hs
retrie: user error ((RealSrcSpan SrcSpanOneLine "Issue16.hs" 6 17 18,"parse error on input \8216@\8217"))
```

**Comment by pepeiborra** [comment]
I think that’s expected. Ghci will fail to parse this file too. 

Have you tried adding a TypeApplications language pragma?

**Comment by anka-213** [comment]
Oh, right. Oops. I had `TypeApplications` in my cabal file and didn't tell retrie about it.

How do I make retrie aware of my cabal file?

**Comment by anka-213** [comment]
The surprising thing is that it doesn't complain when I replace `Proxy` with a function. I guess it worked by pure luck or interpreting it as pattern syntax or something then.

**Comment by pepeiborra** [comment]
I have integrated retrie in hls 0.3.0 which is about to be released soon and should do what you want.

**Comment by anka-213** [comment]
Sweet! Thanks!
