### ISSUE TITLE
Probably better to rename the "demo" executable to "retrie-demo" or something descriptive

### ISSUE THREAD

**Issue by moll** [facebookincubator/retrie#20]
Hey!

Thanks for maintaining Retrie. I noticed it comes with an example [executable named `demo`](https://github.com/facebookincubator/retrie/blob/master/retrie.cabal#L117) that gets built by default if one is after Retrie's CLI. Using Cabal to install it to the home folder also symlinks `demo` to `.cabal/bin`. As `demo` is relatively non-descriptive and likely to clash with other binaries on the system, I think it'd be better either to disable building example/demo binaries by default or rename it at least to `retrie-demo` or something equivalent.

Cheers,

Andri

**Comment by watashi** [comment]
This sounds very reasonable. Feel free to send a pull request.
