### ISSUE TITLE
Full support for windows

### ISSUE THREAD

**Issue by jneira** [facebookincubator/retrie#21]
* From https://github.com/haskell/haskell-language-server/issues/533, where i tried retrie via the haskell-language-server in windows
* It seems `retrie` assumes you are running it in a posix environment with acess to `grep`, `xargs` and, afaics, cli executions with specific sh syntax

<details> <summary> ` retrie -v 2 --rule-forward  MyModule2.myRule` in powershell </summary>

 ```
PS D:\dev\ws\haskell\cabal-test\src> retrie -v 2 --rule-forward  MyModule2.myRule                                                 hgIgnorePred: hg: readCreateProcessWithExitCode: does not exist (No such file or directory)
gitIgnorePred: fatal: not a git repository (or any of the parent directories): .git

Reading VCS ignore failed! Continuing without ignoring.
stdin:

shellCmd:
grep -R --include="*.hs" -l 'infix' D:\dev\ws\haskell\cabal-test\src
Files:
Imports:
Adding:
["x"]
 myMaybe Nothing Just x
==>
 x
hgIgnorePred: hg: readCreateProcessWithExitCode: does not exist (No such file or directory)
gitIgnorePred: fatal: not a git repository (or any of the parent directories): .git

Reading VCS ignore failed! Continuing without ignoring.
stdin:

shellCmd:
grep -R --include="*.hs" -l 'myMaybe[[:space:]]\+Nothing[[:space:]]\+Just' D:\dev\ws\haskell\cabal-test\src
Files:
Done! 0 lines changed.
```

</details>

* If you executes retrie in a msys2 shell, it works as intended but windows users dont have all bash executables in `%PATH%` by default (for good reasons). Ot they have not installed it at all.

<details> <summary> ` retrie -v 2 --rule-forward  MyModule2.myRule` in msys2 bash</summary>

 ```
$ retrie -v 2 --rule-forward MyModule2.myRule
hgIgnorePred: hg: readCreateProcessWithExitCode: does not exist (No such file or directory)
gitIgnorePred: fatal: not a git repository (or any of the parent directories): .git

Reading VCS ignore failed! Continuing without ignoring.
stdin:

shellCmd:
grep -R --include="*.hs" -l 'infix' D:\dev\ws\haskell\cabal-test\src
Files:
Imports:
Adding:
["x"]
 myMaybe Nothing Just x
==>
 x
hgIgnorePred: hg: readCreateProcessWithExitCode: does not exist (No such file or directory)
gitIgnorePred: fatal: not a git repository (or any of the parent directories): .git

Reading VCS ignore failed! Continuing without ignoring.
stdin:

shellCmd:
grep -R --include="*.hs" -l 'myMaybe[[:space:]]\+Nothing[[:space:]]\+Just' D:\dev\ws\haskell\cabal-test\src
Files:
D:\dev\ws\haskell\cabal-test\src\MyModule2.hs
Processing:
D:\dev\ws\haskell\cabal-test\src\MyModule2.hs
Writing: D:\dev\ws\haskell\cabal-test\src\MyModule2.hs (1 lines changed)
Done! 1 lines changed.
```

</details>

* Ideally retrie should at least fallback to a os agnostic grep, even if it is slower 

Thanks in advance!

**Comment by pepeiborra** [comment]
We could remove the dependency on `xargs` (and eventually `grep` too) by replacing them with Haskell. 

Are you interested in sending a PR to do that for `xargs`?

**Comment by jneira** [comment]
> Are you interested in sending a PR to do that for xargs?

I would like to work on that but i am afraid i am not sure when can i start to do it.

`xargs` is showed up in the retrie plugin usage, but no using the executable directly, where only `grep` seems to be used.
So maybe only fixing `xargs` is not enough.
The culprit with the executable is simply using `'` as delimiters, not supported by grep in windows:

```
D:\dev\ws\haskell\cabal-test\src>grep -R --include="*.hs" -l 'myMaybe[[:space:]]\+Nothing[[:space:]]\+Just' D:\dev\ws\haskell\cabal-test\src

D:\dev\ws\haskell\cabal-test\src>grep -R --include="*.hs" -l "myMaybe[[:space:]]\+Nothing[[:space:]]\+Just" D:\dev\ws\haskell\cabal-test\src
D:\dev\ws\haskell\cabal-test\src/MyModule2.hs
```

> We could remove the dependency on xargs (and eventually grep too) by replacing them with Haskell.

That would be great. Not sure if haskell could match the speed of grep, even taking in account the cost of calling an external executable. To investigate!

**Comment by jneira** [comment]
I think this can be closed as the dep of xargs seems to be removed and retrie supports windows nowadays (CC @Tarmean)
