### ISSUE TITLE
Pattern documentation

### ISSUE THREAD

**Issue by 414owen** [facebookincubator/retrie#22]
The minimal example of what I'm trying to do, is to get the the adhoc rule `forall a. 2 : a` to match the expression `[1, 2, 3]`.
There are command line options for enabling pattern synonyms, I couldn't get it working.
It would be great to add this use case to the readme.

Thanks for working on this tool. `retrie` helps me a lot.

**Comment by pepeiborra** [comment]
I'm not sure I understand. Perhaps you could PR a failing test that shows exactly what you are trying to do?

**Comment by 414owen** [comment]
closed in favor of https://github.com/facebookincubator/retrie/pull/23
