### ISSUE TITLE
Upper bounds on optparse-applicative and ansi-terminal can be relaxed

### ISSUE THREAD

**Issue by maralorn** [facebookincubator/retrie#24]

**Comment by pepeiborra** [comment]
@maralorn thanks! Do you happen to know which versions?

**Comment by maralorn** [comment]
According to https://packdeps.haskellers.com/feed?needle=retrie
ansi-terminal 0.11
and
optparse-applicative 0.16.1.0
we build hls with those versions in nixpkgs and it works.

**Comment by pepeiborra** [comment]
The bounds are relaxed in version 1.0.0.0
