### ISSUE TITLE
GHC 9.0.1 Unsupported

### ISSUE THREAD

**Issue by selkie-diligent** [facebookincubator/retrie#25]
Retrie does not build under GHC 9.0.1 and base 4.15.
Please add support for GHC Version 9.0.1.

**Comment by pepeiborra** [comment]
Would you care to submit a PR? I would be happy to review and merge it, as long as it preserves backwards compatibility with GHC 8.8 and newer

**Comment by xich** [comment]
Just a heads up. I'm working on GHC 9 support currently.

**Comment by anka-213** [comment]
@xich Is your progress so far publicly available somewhere? I'm working on getting ghc9 support for haskell-language-server and this is an important dependency.

**Comment by xich** [comment]
@anka-213 I pushed my progress to https://github.com/xich/retrie/commit/06f8cdfc5de4b488e8b4a09c9201172e7e4c45ae

It's pretty close at this point. It's mostly a mechanical process of matching changes to the AST data types.

I could probably get it over the line tonight if it's blocking you. (I'm still on parental leave for another week, so have just been chipping away at this before bed each night.)

**Comment by anka-213** [comment]
Sweet! No rush, I still have other things I can work on before it. I mostly just wanted to know the progress. 😃
