### ISSUE TITLE
Parentheses around sections are not preserved in `--adhoc 'forall a. a . id = a'`

### ISSUE THREAD

**Issue by watashi** [facebookincubator/retrie#35]
Parentheses around sections are not preserved in some rewrites, this leads to invalid code produced by retrie. To repro:

```
$ cat main.hs
main = let f = (+1) . id in print $ f 1
$ runghc main.hs
2
$ retrie --adhoc 'forall a. a . id = a'
$ runghc main.hs

main.hs:1:16: error: parse error on input ‘+’
  |
1 | main = let f = +1 in print $ f 1
  |                ^

```

**Comment by xich** [comment]
This is similar to #34. I'll look into it too.

Aside: is there some permission I need to this repo now so I can do things like assign issues to myself, etc?

**Comment by watashi** [comment]
> Aside: is there some permission I need to this repo now so I can do things like assign issues to myself, etc?

I think I can add you as an "External Contributor" with write permission (not sure if this affects sync) or triage permission.
You need sign the CLA first so I can do that in oss tool though :-)

**Comment by xich** [comment]
> You need sign the CLA first so I can do that in oss tool though :-)

Hahahahahahahahahhaha. Done.
