### ISSUE TITLE
Support GHC 9.2

### ISSUE THREAD

**Issue by fendor** [facebookincubator/retrie#36]
GHC 9.2 rc1 is out, and `ghcide` aims to implement GHC 9.2 support ASAP.

The last dependency of `ghcide` that doesn't compile with GHC 9.2 (via [head.hackage](https://gitlab.haskell.org/ghc/head.hackage)) is `retrie` and it would be great if we could upgrade soon!

**Comment by pepeiborra** [comment]
@fendor would you be interested in sending a PR? I can get it merged next week and release to Hackage

**Comment by fendor** [comment]
I'll have a crack at it tomorrow!

**Comment by fendor** [comment]
Unfortunately, I failed to upgrade to latest ghc-exactprint and can't promise a PR any time soon.

**Comment by pepeiborra** [comment]
Maybe we should look into dropping the dependency from ghcide then?

**Comment by alanz** [comment]
@fendor Is your work in progress available anywhere? I am keen to give this a go, to confirm that the new ghc-exactprint actually works.

**Comment by alanz** [comment]
And I believe the only sane way forward is as with ghc-exactprint, the current version works for GHC < 9.2, a later one supports GHC 9.2 and up.

**Comment by fendor** [comment]
I pushed my WIP to https://github.com/fendor/retrie/tree/wip/ghc92, but don't expect much, I struggled with understanding what changed between ghc-exactprint versions, and what has moved to GHC, etc...

**Comment by mouse07410** [comment]
> Maybe we should look into dropping the dependency from `ghcide` then?

I'd say it would be the best. Ideal.

**Comment by pepeiborra** [comment]
> > Maybe we should look into dropping the dependency from `ghcide` then?
> 
> I'd say it would be the best. Ideal.

Thanks for your input. Unfortunately the challenge here is created by the new encoding of ghc-exactprint included in ghc-9.2 and not so much by retrie, so dropping the retrie dependency would only make things worse for ghcide, since we'd need to deal with ghc-exactprint ourselves.

**Comment by alanz** [comment]
FWIW, I have an updated ghc-exactprint for GHC 9.2.1, not released yet.  There are a few minor niggles.
I think it may be best to publish it, and my update for retrie to use it, so that the build gets unblocked.
It will have a few infelicities, which can be solved later, but will at least not block the bigger project.

**Comment by mouse07410** [comment]
@alanz yes, please do publish it!

**Comment by alanz** [comment]
I am down to ten failing tests, end is in sight, will get something out on the weekend at the latest (failing or not)

**Comment by Dessix** [comment]
@alanz Was there any progress on this-- a branch we can track and contribute to, perhaps? This issue is blocking a significant portion of potential developers from adopting GHC 9.2+, and the weekend you mentioned has passed.

**Comment by alanz** [comment]
My branch is at https://github.com/alanz/retrie/tree/ghc-9.2, but it needs https://github.com/alanz/ghc-exactprint/tree/separate-priorends too.

I plan on making a fresh ghc-exactprint release tomorrow, which will allow prodress on this.

Ping @xich

**Comment by xich** [comment]
I've managed to get your branches building and failing the one test we've discussed. I'll see if I can get it passing.

**Comment by alanz** [comment]
I just published [ghc-exactprint-1.3.0](https://hackage.haskell.org/package/ghc-exactprint-1.3.0)

**Comment by alanz** [comment]
The last formatting failure is from the fixity processing.

@xich are you ok with me moving the fixity re-alignment into ghc-exactprint?  I intend making a new home for the fixity data from haskell-src-exts too.

And I intend pushing chunks from the Retrie.ExactPrint module into ghc-exactprint too, as being generally useful.

**Comment by xich** [comment]
> are you ok with me moving the fixity re-alignment into ghc-exactprint?

Please do! Anything that makes sense to move is good with me.

**Comment by pepeiborra** [comment]
retrie 1.2.0.0 is on Hackage with experimental support for GHC 9.2. For earlier GHC versions, stick to retrie 1.1.0.0
