### ISSUE TITLE
Error message when working on GHC sources is unhelpful

### ISSUE THREAD

**Issue by nrnrnr** [facebookincubator/retrie#41]
I'm trying to use `retrie` to refactor the GHC sources.  Operating in the `compiler` subdirectory of the GHC gitlab root, I ran an ad-hoc rule with this result:

```
retrie --adhoc "forall x . not (backendNeedn'tLink x) == backendNeedsLink x"

parseAdhocs:1:80: error: parse error on input ‘#-}’
retrie: user error (parse failed)
```

From this error message, I can't tell if there's a problem with my rule, a problem with the GHC sources, or a problem with `retrie`.  For starters, it would be useful to know the source location at which the offending `#-}` was observed.

**Comment by pepeiborra** [comment]
Thanks for the issue report. 

I think the problem here is in the adhoc rule - the double equal `==` seems to be confusing the parser. This works better:

```
retrie --adhoc "forall x . not (backendNeedn'tLink x) = backendNeedsLink x"
```

**Comment by nrnrnr** [comment]
Ah!  Thank you.

It still doesn't work very well because of the `'` character in the function's name.  I am going to try to submit a pull request to fix that.
